url: http://www.runforlearning.com

org_name: Run For Learning

name: Run For Learning 5K Run/Walk and Kids Fun Run

short_name: 5K Run/Walk and Kids Fun Run

description: 5K Run/Walk and Kids Fun Run to raise funds for two Grayslake pre-schools

author_email: webmaster@grayslake-coop.com

running: "3<sup>rd</sup> Annual"

event_year: "2016"

event_date: "September 24<sup>th</sup>, 2016"

event_date_long: "Saturday, September 24<sup>th</sup>, 2016"

packet_pickup_start_date_long: "Friday, September 23<sup>rd</sup>, 2016"

event_location: "Downtown Grayslake, IL"

registration_url: 'registration.html'

registration_vendor_url: "https://www.signmeup.com/109360"

registration_vendor_link: '<a href="https://www.signmeup.com/109360" class="btn btn-danger btn-lg" disabled="disabled" target="_blank">Register Online Now!</a>'

registration_link: '<a href="registration.html" class="btn btn-danger btn-lg">Register Now!</a>'

registration_form_url: '/assets/files/2015_RunForLearning_registration_form.pdf'

registration_form_link: '<a href="/assets/files/2015_RunForLearning_registration_form.pdf" alt="2015 Run For Learning Registration Form" target="_blank"><i class="fa fa-file-pdf-o"></i> registration form</a>'

grant_form_url: '/assets/files/2016/rfl_grant_application_v1a.pdf'

sponsor_link: '<a href ="/sponsor.html" class="btn btn-success btn-lg">Become a Sponsor</a>'

facebook_url: 'https://www.facebook.com/runforlearning5k'

contact_email: 'runforlearning@gmail.com'

contact_phone: '(224) 419-4023'

contact_phone_unformatted: '2244194023'

sponsorship_form_url: '/assets/files/2016/rfl_5k_sponsorship_form_v1.pdf'

logo_image: '<img src="/assets/images/run_for_learning_logo_2015.png" alt="Run for Learning logo"/>'

2014_logo_image: '<img src="/assets/images/run_for_learning_logo_2014.jpg" alt="Run for Learning logo"/>'

gcns_url: 'http://www.grayslake-coop.com/'

gcns_logo_url: '/assets/images/gcns_logo.jpg'

gloryland_url: 'http://www.glorylandpreschool.com/'

gloryland_logo_url: '/assets/images/gloryland_logo.jpg'

westlake_url: 'http://westlakechristian.org/'

westlake_logo_url: '/assets/images/westlakechristian_logo.jpg'

peppermint_url: 'http://peppermintstickcc.com'

peppermint_logo_url: '/assets/images/peppermint_stick_logo.jpg'

four_kids_url: 'http://www.4kidsclc.com/index.php'

four_kids_logo_url: '/assets/images/trade_sponsors/4-kids-logo.jpg'

marys_peppermint_url: 'http://maryspeppermintstick.org/'

marys_peppermint_logo_url: '/assets/images/trade_sponsors/marys_peppermint_logo.png'

tt_url: 'http://www.wildwoodpc.net/preschool/'

tt_logo_url: '/assets/images/tiny_treasures_logo.jpg'

race_results_5k_2014: '<a href="http://racetime.info/wp-content/uploads/2014/09/Run-For-Learning-5K-Overall-Results.htm" title="Run for Learning 5K 2014 Race Results" class="btn btn-success btn-lg" target="_blank">5K race results</a>'

race_results_1k_2014: '<a href="http://racetime.info/wp-content/uploads/2014/09/Run-For-Learning-1K-Youth-Overall-Results.htm" title="Run for Learning 1K 2014 Race Results" class="btn btn-success btn-lg" target="_blank">1K race results</a>'

race_results_5k_2015: '<a href="http://www.racetime.info/wp-content/uploads/2015/09/Run-For-Learning-5K-Overall-Results.htm" title="Run for Learning 5K 2015 Race Results" class="btn btn-success btn-lg" target="_blank">5K race results</a>'

race_results_1k_2015: '<a href="http://www.racetime.info/wp-content/uploads/2015/09/Run-For-Learning-Youth-Run.htm" title="Run for Learning 1K 2015 Race Results" class="btn btn-success btn-lg" target="_blank">1K race results</a>'

exclude: [README.md, tags, vendor]

